### PR TITLE
L5 compatibility (view loading, lang loading, removed package-registration)

### PR DESCRIPTION
**Pull request by mosanger**

### CODE REVIEW

**Comment by haampie** [comment]
+1

**Comment by pgtruesdell** [comment]
+1

I've been using this for a few days in production and it's working perfectly. Would be great if it was merged.

**Comment by msurguy** [comment]
@pgtruesdell, @mosanger could you please confirm that it still works in Laravel 4 with this code? I'll merge as soon as I get a confirmation...

**Comment by pgtruesdell** [comment]
Due to changes in Laravel 5, the changes are not backwards compatible. The best option I've seen is to designate a major version number to L5 and document it in the readme.

**Comment by mosanger** [comment]
It's also possible to call service provider methods depending on Laravel's
version.
Or even provide different Service Providers for either L4 or L5.
It really depends on which way you want to go.

Paul Grant Truesdell, II <notifications@github.com> schrieb am Thu Feb 19
2015 at 03:30:39:

**Comment by msurguy** [comment]
@pgtruesdell Ok in that case I'll create a new release of the package and this will have to be merged into the new release

**Comment by haampie** [comment]
When will it be merged?

**Comment by graystevens** [comment]
+1

**Comment by sdebacker** [comment]
+1

**Comment by luisdalmolin** [comment]
If the compatibility it's going to be a problem, we should make a new package.

**Comment by garygreen** [comment]
There's no need to make a new package. You can check versions in the service provider and decide what functions to call for Laravel 5 and 4. Very little has to be changed really. I'll create another PR if you like @msurguy ?

**Comment by msurguy** [comment]
Thanks to @garygreen this PR : https://github.com/msurguy/Honeypot/pull/21 has been merged! @mosanger feel free to branch off master and implement some of your code from this PR in that updated branch now :)

**Comment by mosanger** [comment]
should be good to go now

**Comment by sdebacker** [comment]
What about a new release ?

**Comment by garygreen** [comment]
@mosanger the view was removed in a recent commit I did, so only thing you possibly need is just to fix spaces/tabs. Might be unnecessary though.

+1 to new release tag :+1:

**Comment by mosanger** [comment]
yeah, i just noticed. sorry for the confusion

Gary Green <notifications@github.com> schrieb am Mi., 18. März 2015 um
13:20 Uhr:

**Comment by garygreen** [comment]
You might also want to squash the 4 commits down and amend commit name to simply 'Cleanup tabs/spaces'

**Comment by mosanger** [comment]
honestly, it doesn't have to be merged at all now.

**Pull request closed without merging**
