### PR TITLE
Support Laravel 5.5's Auto-Discovery

### PR DESCRIPTION
**Pull request by juukie**

### CODE REVIEW

**Comment by DevDavido** [comment]
+1 Would be great if you could merge it @msurguy

**Comment by msurguy** [comment]
Thanks @juukie !

**Comment by juukie** [comment]
Thanks for merging Maksim

**Comment by upwebdesign** [comment]
Would be nice if there was a release with this merge in it :) @msurguy Been using this package for years now, thanks!

**Comment by juukie** [comment]
@upwebdesign Yeah the release never came. However, I recommend using https://github.com/spatie/laravel-honeypot :-)

**Comment by upwebdesign** [comment]
@juukie Oh, wow, I did not realize, Ive always used this package! Thanks for the heads up!

**Comment by msurguy** [comment]
@upwebdesign @juukie I did a new release last night and tested in my own L5.7 project, works really well! 

But I would still echo @juukie's advice and use a better package instead if this one doesn't serve you well. 
Thanks all!

**Comment by juukie** [comment]
Thanks @msurguy, i still use it in older projects :+1:. For newer project I use Spatie’s since I know they are more activve in the PHP world :-)

**Comment by msurguy** [comment]
@juukie fair point! I've been out of the dev scene for the past two years but believe it or not, I'm coming back to full stack development on my new job right now!

**Pull request merged**
