### PR TITLE
Added required package illuminate/html

### PR DESCRIPTION
**Pull request by sdebacker**
But this package is deprecated… It would be nice to remove this dependency.

### CODE REVIEW

**Comment by garygreen** [comment]
Well technically it's not required at all now. You can instantiate honeypot manually and get the html. All the illuminate/html would be for is to add a macro `honeypot` to the FormBuilder. More of a shortcut/usage preference. I'm -1 to this PR, though I think it might be useful to add it in a `suggests` instead.

As for Laravel Collective, I think it's not currently supported, though you can use the Honeypot facade for now.

**Comment by sdebacker** [comment]
Ok, you are right.

**Comment by sdebacker** [comment]
I finally created my own package based on this one : https://github.com/TypiCMS/Honeypot

**Comment by garygreen** [comment]
PR #35 will solve this issue so not really necessary to maintain another package but fair enough.

**Comment by msurguy** [comment]
This package has been updated now to 1.0.0 version.

**Comment by sdebacker** [comment]
Thank you Maksim, I deleted my fork !

**Pull request closed without merging**
