### PR TITLE
Adding translation for Spanish

### PR DESCRIPTION
**Pull request by JuanDMeGon**
Just a little addition that would be great for Spanish websites.

### CODE REVIEW

**Comment by JuanDMeGon** [comment]
If it is valid and you don't mind, would be great if it can be tagged as "hacktoberfest-accepted".

I hope it helps just a little 💯

**Comment by msurguy** [comment]
Thanks @JuanDMeGon ! 
hacktoberfest-accepted!

**Comment by JuanDMeGon** [comment]
Thanks! I am glad it helped.

For future reference, in case the repo receives any future Hacktoberfest PR, those are the rules to consider it accepted:
image
Best wishes.

**Comment by msurguy** [comment]
@JuanDMeGon thanks, added the label to the PR

**Pull request merged**
